Make the editor work mouse-based, not keyboard-based.
Exception: +/- still needed to edit allowed changes.

Bug: if you copy with the mouse over the level, it copies whatever type
of tile you're currently placing instead of what's actually there.